apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: django-app
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: restauappacr.azurecr.io/django-app # Replace with your own image
          ports:
            - containerPort: 8000  # Port on which your Django app listens
          env:
            - name: DATABASE_HOST
              value: "restau-db-server.postgres.database.azure.com"  # Replace with your Azure PostgreSQL server host
            - name: DATABASE_PORT
              value: "5432"  # Replace with your Azure PostgreSQL server port
            - name: DATABASE_NAME
              value: "restau-db"  # Replace with your PostgreSQL database name
            - name: DATABASE_USER
              value: "restau"  # Replace with your PostgreSQL username
            - name: DATABASE_PASSWORD
              value: 111111amM  # Replace with your PostgreSQL password
---
apiVersion: v1.27
kind: Service
metadata:
  name: django-app-alb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: django-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: namespace-workflow-1687757212665
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: Azure Kubernetes Service RBAC Cluster Admin
subjects:
- kind: Group
  name: Ndambi Desmond Group



